apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
  namespace: temperatura
spec:
  selector:
    matchLabels:
      app: conversao-temperatura
  replicas: 1
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
        - name: conversao-temperatura
          image: lportinari/conversao-temperatura:latest
          ports:
            - containerPort: 8080
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
  namespace: temperatura
spec: 
  selector:
    app: conversao-temperatura
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
          
    
